kubernetes:
  url: https://github.com/kubernetes/kubernetes
  ref: master
  sha: b910026535af2d8a64d45efefeb8d9efb75a4817

containerd:
  url: https://github.com/containerd/containerd
  ref: main
  sha: 574a80c45f530d0ada7799c9373940b2e2ecee07
