name: Dependencies

on:
  push:
    branches:
      - main
      - 'pull-request/[0-9]*'
    paths:
      - 'config.yaml'
      - '.github/actions/**'
      - 'projects/kubernetes/**'
      - '.github/workflows/dependencies.yml'
  pull_request:
    branches: [main]
    paths:
      - 'config.yaml'
      - '.github/actions/**'
      - 'projects/kubernetes/**'
      - '.github/workflows/dependencies.yml'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependencies:
    runs-on: ${{ github.repository == 'dims/test-k8s' && 'ubuntu-24.04' || 'linux-amd64-cpu8' }}
    timeout-minutes: 30
    env:
      ARTIFACTS: ${{ github.workspace }}/_artifacts
      GOPATH: ${{ github.workspace }}/go
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - id: config
        uses: ./.github/actions/load-config
      - uses: ./.github/actions/cleanup-disk
      - uses: ./.github/actions/setup-kubernetes
        with:
          repository: ${{ steps.config.outputs.kubernetes-repo }}
          ref: ${{ steps.config.outputs.kubernetes-sha }}
          path: go/src/k8s.io/kubernetes
          fetch-depth: 0
          patches-dir: projects/kubernetes
      - uses: ./.github/actions/report-revisions
        with:
          kubernetes-repo: ${{ steps.config.outputs.kubernetes-repo }}
          kubernetes-ref: ${{ steps.config.outputs.kubernetes-ref }}
          kubernetes-sha: ${{ steps.config.outputs.kubernetes-sha }}
          containerd-repo: ${{ steps.config.outputs.containerd-repo }}
          containerd-ref: ${{ steps.config.outputs.containerd-ref }}
          containerd-sha: ${{ steps.config.outputs.containerd-sha }}
      - name: Verify Dependencies
        working-directory: go/src/k8s.io/kubernetes
        run: make verify WHAT="external-dependencies-version vendor vendor-licenses"
      - uses: ./.github/actions/collect-logs
        if: always()
        with:
          artifacts-dir: ${{ env.ARTIFACTS }}
          name: dependencies-logs
